#!/bin/sh

set -ex
old_commit_message=$(git log -1 --pretty=%B)
repo_url="https://csarubot:xWIlUg8RG7RfIJUmZbfeLjNOUZxAseFNMkW8jmYu@github.com/csaru/csaru.github.io.git"
git clone "$repo_url" _oldsite
rsync -a --delete --exclude .git/ _site/ _oldsite/
cd _oldsite
git add --all
git commit -m "$old_commit_message"
git push "$repo_url"
